name: Package files
on: [push]
jobs:
  package:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: mkdir -p dist
      - uses: robinraju/release-downloader@v1.8
        with:
          repository: trumank/uesave-rs
          tag: v0.3.0
          fileName: uesave-x86_64-pc-windows-msvc.zip
          out-file-path: dist/uesave
          extract: true
      - shell: bash
        run: |
          cp LICENSE dist/
          cp README.md dist/
          cp *.py dist/
          cp -r lib dist/
          cp convenience_tools/* dist/
          cd dist
          zip -r ../palworld-save-tools-windows.zip *
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          files: |
            palworld-save-tools-windows.zip
